/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.1 Update 1
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2017 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "SPI_Master.h"
#include "SPI_Master_SPI_UART.h"
#include "SPI_Master_PINS.h"
#include "SPI_Master_SPI_UART_PVT.h"
#include "SPI_Master_PVT.h"
#include "SPI_Master_BOOT.h"
#include "LCD_DC.h"
#include "LCD_DC_aliases.h"
#include "LCD_Reset.h"
#include "LCD_Reset_aliases.h"
#include "SPI_Master_SCBCLK.h"
#include "SPI_Master_sclk_m.h"
#include "SPI_Master_sclk_m_aliases.h"
#include "SPI_Master_mosi_m.h"
#include "SPI_Master_mosi_m_aliases.h"
#include "SPI_Master_ss0_m.h"
#include "SPI_Master_ss0_m_aliases.h"
#include "core_cm0_psoc4.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cyPm.h"
#include "cytypes.h"
#include "cypins.h"
#include "CyDMA.h"
#include "CyLFClk.h"

/*[]*/

